on:
  push:
    branches:
      - main
      - develop

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build wheel and install
        run: |
          python -m pip install --user --upgrade build
          python -m build
      - name: archive build artifacts
        uses: actions/upload-artifact@v3
        with:
            name: dist-files
            path: dist/*
#          #pip install .
#          find ./dist/*.whl | xargs pip install
#          python simple_test.py
#      - name: Configure Git
#        run: |
#          git config --global user.email "apwheele@gmail.com"
#          git config --global user.name "apwheele"
#      - name: Commit and push wheel
#        run: |
#          git add -f ./dist/*.whl
#          git commit -m 'pushing new wheel'
#          git push
